Repository Jahia/moonstone, pull requests merged in 2020-02, with the labels that each got.

#55 MOON-55: remove undefined height:100%
  .storybook/config.js
  src/components/Accordion/Accordion.jsx
  src/components/Accordion/Accordion.scss
  src/components/Accordion/Accordion.stories.jsx
  src/components/Accordion/AccordionItem/AccordionItem.scss
  src/components/PrimaryNav/PrimaryNav.scss
  src/components/SecondaryNav/SecondaryNav.jsx
  src/components/SecondaryNav/SecondaryNav.scss
  src/components/SecondaryNav/SecondaryNav.stories.jsx
  src/globals/_layout.scss
  src/layouts/app/LayoutApp.jsx
  src/layouts/module/LayoutModule.jsx
Labels: bug, patch

#57 MOON-56: Allow all components to add custom attributes
  src/components/Accordion/Accordion.jsx
  src/components/Accordion/Accordion.spec.js
  src/components/Accordion/AccordionItem/AccordionItem.jsx
  src/components/Button/Button.jsx
  src/components/Button/Button.spec.js
  src/components/PrimaryNav/PrimaryNav.jsx
  src/components/PrimaryNav/PrimaryNav.spec.js
  src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.jsx
  src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.spec.js
  src/components/PrimaryNav/PrimaryNavItemsGroup/PrimaryNavItemsGroup.jsx
  src/components/PrimaryNav/PrimaryNavItemsGroup/PrimaryNavItemsGroup.spec.js
  src/components/ResizableBox/Resizable.spec.js
  src/components/ResizableBox/ResizableBox.jsx
  src/components/SecondaryNav/SecondaryNav.jsx
  src/components/SecondaryNav/SecondaryNav.spec.js
  src/components/Separator/Separator.jsx
  src/components/Separator/Separator.spec.js
  src/components/TreeView/ControlledTreeView.jsx
  src/components/TreeView/TreeView.spec.js
  src/components/Typography/Typography.spec.js
Labels: minor

#48 MOON-41 : Allow SecondaryNav to be hidden
  src/components/ResizableBox/ResizableBox.jsx
  src/components/ResizableBox/ResizableBox.stories.jsx
  src/components/SecondaryNav/SecondaryNav.jsx
  src/components/SecondaryNav/SecondaryNav.scss
  src/components/SecondaryNav/SecondaryNav.spec.js
  src/layouts/app/LayoutApp.stories.jsx
  src/layouts/module/LayoutModule.stories.jsx
  src/tokens/icons/asset/ChevronDoubleLeft.svg
  src/tokens/icons/asset/ChevronDoubleRight.svg
Labels: enhancement, minor

#58 MOON-60: Add a displayName
  src/components/Accordion/Accordion.jsx
  src/components/Accordion/AccordionItem/AccordionItem.jsx
  src/components/Button/Button.jsx
  src/components/GlobalStyle/GlobalStyle.jsx
  src/components/PrimaryNav/PrimaryNav.jsx
  src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.jsx
  src/components/PrimaryNav/PrimaryNavItemsGroup/PrimaryNavItemsGroup.jsx
  src/components/ResizableBox/ResizableBox.jsx
  src/components/SecondaryNav/SecondaryNav.jsx
  src/components/Separator/Separator.jsx
  src/components/TreeView/TreeView.jsx
  src/components/Typography/Typography.jsx
  src/layouts/app/LayoutApp.jsx
  src/layouts/module/LayoutModule.jsx
Labels: internal

#60 MOON-62 update colors
  README.md
  src/tokens/colors/_colors.scss
Labels: patch

#61 MOON-62 fix issue with basic colors
  src/tokens/colors/_colors.scss
Labels: patch

#59 Moon 58: Improve accordion - makes it controllable
  src/components/Accordion/Accordion.jsx
  src/components/Accordion/Accordion.spec.js
  src/components/Accordion/Accordion.stories.jsx
  src/components/Accordion/AccordionItem/AccordionItem.jsx
  src/components/Accordion/AccordionItem/AccordionItem.scss
  src/components/Accordion/AccordionItem/AccordionItem.spec.jsx
  src/components/Accordion/ControlledAccordion.jsx
  src/components/Accordion/UncontrolledAccordion.jsx
Labels: minor

#66 MOON-30: Add github workflow to deploy storybook on github pages
  .github/workflows/deploy-storybook.yml
  README.md
Labels: internal

#69 MOON-67 : Fixed styling, handle root node
  src/components/TreeView/ControlledTreeView.jsx
  src/components/TreeView/TreeView.jsx
  src/components/TreeView/TreeView.md
  src/components/TreeView/TreeView.scss
  src/components/TreeView/TreeView.spec.js
  src/components/TreeView/TreeView.stories.jsx
  src/components/TreeView/UncontrolledTreeView.jsx
Labels: patch

#72 MOON-48: Update API of Typography component
  src/components/Accordion/AccordionItem/AccordionItem.jsx
  src/components/Chip/Chip.jsx
  src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.jsx
  src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.scss
  src/components/TreeView/ControlledTreeView.jsx
  src/components/Typography/Typography.jsx
  src/components/Typography/Typography.scss
  src/components/Typography/Typography.spec.js
  src/components/Typography/Typography.stories.jsx
Labels: minor

#70 Updated css guidelines
  CONTRIBUTING.md
Labels: internal

#56 MOON-12: Create dropdown component
  .eslintrc
  src/components/Button/Button.scss
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/Dropdown.md
  src/components/Dropdown/Dropdown.scss
  src/components/Dropdown/Dropdown.spec.js
  src/components/Dropdown/Dropdown.stories.jsx
  src/components/Dropdown/index.js
  src/components/ListItem/ListItem.jsx
  src/components/ListItem/ListItem.md
  src/components/ListItem/ListItem.scss
  src/components/ListItem/ListItem.spec.js
  src/components/ListItem/ListItem.stories.jsx
  src/components/ListItem/index.js
  src/components/Menu/Menu.jsx
  src/components/Menu/Menu.md
  src/components/Menu/Menu.scss
  src/components/Menu/Menu.spec.js
  src/components/Menu/Menu.stories.jsx
  src/components/Menu/index.js
  src/components/PrimaryNav/PrimaryNav.scss
  src/components/SecondaryNav/SecondaryNav.scss
  src/components/Separator/Separator.jsx
  src/components/Separator/Separator.stories.jsx
  src/components/Typography/Typography.scss
  src/components/index.js
  src/tokens/shadows/_shadows.scss
  src/utils/_helpers.scss
  src/utils/_index.scss
  src/utils/_mixins.scss
  src/utils/index.scss
Labels: minor

#79 Moon 68 Badge component
  src/components/Badge/Badge.jsx
  src/components/Badge/Badge.md
  src/components/Badge/Badge.scss
  src/components/Badge/Badge.spec.js
  src/components/Badge/Badge.stories.jsx
  src/components/Badge/index.js
  src/components/PrimaryNav/PrimaryNav.stories.jsx
  src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.jsx
  src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.scss
  src/components/index.js
  src/layouts/Layouts.stories.jsx
Labels: enhancement, minor

#82 MOON-72: UI/UX button improvement
  src/components/Button/Button.scss
  src/components/Button/variants/_ghost.scss
Labels: skip-release

#81 Moon 70: Update Badge design
  src/components/Badge/Badge.jsx
  src/components/Badge/Badge.scss
  src/components/Badge/Badge.spec.js
  src/components/Badge/Badge.stories.jsx
  src/components/Chip/Chip.jsx
  src/components/PrimaryNav/PrimaryNav.stories.jsx
  src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.jsx
  src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.scss
  src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.stories.jsx
  src/components/PrimaryNav/PrimaryNavItemsGroup/PrimaryNavItemsGroup.stories.jsx
Labels: patch

#83 MOON-40: Remove the deploy script
  package.json
Labels: internal

#89 MOON-36 : split code with custom hooks
  src/components/Menu/Menu.jsx
  src/components/Menu/Menu.stories.jsx
  src/hooks/useEnterExitCallbacks.jsx
  src/hooks/usePositioning.jsx
Labels: internal

#90 MOON-76: Add icons
  src/components/ResizableBox/ResizableBox.jsx
  src/tokens/icons/asset/HandleDrag.svg
  src/tokens/icons/asset/HandleResize.svg
  src/tokens/icons/asset/ViewComfy.svg
  src/tokens/icons/asset/index.js
Labels: patch

#92 Fix warning issue when using mixed prod/dev
  src/components/Typography/Typography.jsx
Labels: internal
