Repository Jahia/moonstone, pull requests merged in 2020-12, with the labels that each got.

#205 MOON-212: Small updates to CircleCI config and typescript naming convention
  .circleci/config.yml
  src/components/Badge/Badge.stories.jsx
  src/components/Badge/Badge.tsx
  src/components/Dropdown/Dropdown.stories.jsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Input/Input.stories.jsx
  src/components/Input/Input.tsx
  src/components/ListItem/ListItem.tsx
  src/components/Menu/Menu.tsx
  src/components/Menu/MenuItem.tsx
  src/components/Separator/Separator.stories.jsx
  src/components/Separator/Separator.tsx
  src/components/Typography/Typography.tsx
Labels: patch

#206 MOON-212: Adjustment to commands adding github.com to ssh known hosts
  .circleci/config.yml
  .github/workflows/deploy-storybook.yml
  package.json
Labels: patch

#208 MOON-217: Update dependencies
  .storybook/addons.js
  .storybook/main.js
  .storybook/manager.js
  .storybook/preview.js
  .storybook/webpack.config.js
  .stylelintrc.json
  package.json
  src/components/Accordion/Accordion.stories.jsx
  src/components/Accordion/AccordionItem/AccordionItem.scss
  src/components/Accordion/AccordionItem/AccordionItem.stories.jsx
  src/components/Badge/Badge.stories.jsx
  src/components/Breadcrumb/Breadcrumb.stories.jsx
  src/components/Button/Button.stories.jsx
  src/components/ButtonGroup/ButtonGroup.stories.jsx
  src/components/Chip/Chip.stories.jsx
  src/components/Dropdown/Dropdown.stories.jsx
  src/components/GlobalStyle/GlobalStyle.stories.jsx
  src/components/ImgWrapper/ImgWrapper.stories.jsx
  src/components/Input/Input.stories.jsx
  src/components/ListItem/ListItem.stories.jsx
  src/components/Menu/Menu.stories.jsx
  src/components/PrimaryNav/PrimaryNav.stories.jsx
  src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.scss
  src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.stories.jsx
  src/components/PrimaryNav/PrimaryNavItemsGroup/PrimaryNavItemsGroup.stories.jsx
  src/components/ResizableBox/ResizableBox.stories.jsx
  src/components/SecondaryNav/SecondaryNav.stories.jsx
  src/components/Separator/Separator.stories.jsx
  src/components/SvgWrapper/SvgWrapper.stories.jsx
  src/components/Tab/Tab.stories.jsx
  src/components/TabItem/TabItem.stories.jsx
  src/components/TreeView/TreeView.stories.jsx
  src/components/Typography/Typography.stories.jsx
  src/icons/Icons.stories.jsx
  src/layouts/Layouts.stories.jsx
  src/layouts/app/LayoutApp.stories.jsx
  src/layouts/module/LayoutModule.stories.jsx
  src/tokens/colors/color.stories.jsx
  src/tokens/spacings/spacing.stories.jsx
  src/utils/_mixins.scss
  src/utils/_typography.scss
  webpack.config.js
  yarn.lock
Labels: internal

#207 MOON-216: Fixes menu truncation issue in Firefox and Safari
  package.json
  src/components/Dropdown/Dropdown.tsx
Labels: patch

#210 MOON-216: Increase minimum width for dropdown menu to 80px
  src/components/Dropdown/Dropdown.tsx
Labels: patch

#211 MOON-218: Skip CI for gh-pages branch
  .circleci/config.yml
  .github/workflows/deploy-storybook.yml
Labels: internal

#212 MOON-216: Adds webpack publicPath to fix test issues
  webpack.config.js
Labels: patch

#213 MOON-219: Fix error when an empty array is used as data on dropdown
  src/components/Dropdown/Dropdown.spec.js
  src/components/Dropdown/Dropdown.tsx
Labels: bug

#214 Add babel-helpers
  babel.build.config.js
  package.json
  yarn.lock
Labels: internal

#215 MOON-228: Allow displaying dropdown with an empty array
  src/components/Dropdown/Dropdown.spec.js
  src/components/Dropdown/Dropdown.stories.jsx
  src/components/Dropdown/Dropdown.tsx
Labels: bug

#216 MOON-223: Fix Dropdown Menu positioning in modals
  README.md
  src/components/Dropdown/Dropdown.scss
  src/components/Dropdown/Dropdown.tsx
  src/components/Menu/Menu.md
  src/components/Menu/Menu.scss
  src/components/Menu/Menu.stories.jsx
  src/components/Menu/Menu.tsx
  src/hooks/usePositioning.tsx
Labels: major

#217 MOON-229: Revert back some changes to Github pages deployment
  .github/workflows/deploy-storybook.yml
Labels: internal
