Repository Jahia/moonstone, pull requests merged in 2020-10, with the labels that each got.

#182 MOON-156: Migrates MenuItem to Typescript and Adds Images
  src/components/ListItem/ListItem.scss
  src/components/ListItem/ListItem.stories.jsx
  src/components/ListItem/ListItem.tsx
  src/components/ListItem/index.ts
  src/components/Menu/Menu.stories.jsx
  src/components/Menu/MenuItem.jsx
  src/components/Menu/MenuItem.scss
  src/components/Menu/MenuItem.tsx
  src/components/Menu/index.ts
Labels: enhancement

#184 MOON-169: Adds Menu Variants for Small and Big Images
  src/components/Menu/Menu.scss
  src/components/Menu/Menu.stories.jsx
  src/components/Menu/Menu.tsx
Labels: hacktoberfest-accepted, patch

#185 MOON-159: Migrates Dropdown to Typescript
  src/components/Dropdown/Dropdown.stories.jsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/index.ts
  src/components/Menu/Menu.tsx
  src/components/Menu/MenuItem.tsx
  src/components/Separator/index.ts
  tsconfig.json
  tslint.json
Labels: hacktoberfest-accepted, patch

#186 MOON-198: Adds ability to search in Menu
  src/components/Input/Input.md
  src/components/Menu/Menu.md
  src/components/Menu/Menu.scss
  src/components/Menu/Menu.stories.jsx
  src/components/Menu/Menu.tsx
Labels: hacktoberfest-accepted, patch

#187 MOON-199: Run typescript lint script for PRs
  .github/workflows/lint-test.yml
Labels: hacktoberfest-accepted, skip-release

#188 MOON-160: Adds ability to have image dropdown options
  src/components/Dropdown/Dropdown.md
  src/components/Dropdown/Dropdown.scss
  src/components/Dropdown/Dropdown.stories.jsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Menu/Menu.scss
  src/components/Menu/Menu.stories.jsx
  src/components/Menu/Menu.tsx
Labels: hacktoberfest-accepted, skip-release

#189 MOON-161: Styling for outlined Dropdown variant
  src/components/Dropdown/Dropdown.scss
  src/components/Dropdown/Dropdown.stories.jsx
  src/components/Dropdown/Dropdown.tsx
Labels: hacktoberfest-accepted, skip-release

#190 MOON-200: Add the new icon Tips
  package.json
  src/icons/Tips.tsx
  src/icons/assets.ts
  src/tokens/icons/assets/Tips.svg
  src/tokens/icons/svgr.config.json
Labels: hacktoberfest-accepted, patch

#191 MOON-201: Fixes issue with searching when Dropdown Menu has groups
  src/components/Dropdown/Dropdown.md
  src/components/Dropdown/Dropdown.tsx
  src/components/Menu/Menu.tsx
Labels: bug, hacktoberfest-accepted

#193 Removes .npmrc to remove connection to Jahia npm registry
  .npmrc
Labels: hacktoberfest-accepted, skip-release
