Repository Jahia/moonstone, pull requests merged in 2020-03, with the labels that each got.

#100 MOON-83: Fix PrimaryNav's icon alignment
  src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.scss
Labels: bug

#99 Moon 36: Add active state to MenuItem
  src/components/ButtonGroup/ButtonGroup.stories.jsx
  src/components/Dropdown/Dropdown.jsx
  src/components/ListItem/ListItem.jsx
  src/components/ListItem/ListItem.scss
  src/components/Menu/MenuItem.jsx
  src/components/Menu/MenuItem.scss
Labels: bug

#104 BACKLOG-12504 add Img and Svg wrapper to return icon sized image
  src/components/ImgWrapper/ImgWrapper.jsx
  src/components/ImgWrapper/ImgWrapper.md
  src/components/ImgWrapper/ImgWrapper.spec.jsx
  src/components/ImgWrapper/ImgWrapper.stories.jsx
  src/components/ImgWrapper/index.js
  src/components/SvgWrapper/SvgWrapper.jsx
  src/components/SvgWrapper/SvgWrapper.md
  src/components/SvgWrapper/SvgWrapper.spec.jsx
  src/components/SvgWrapper/SvgWrapper.stories.jsx
  src/components/SvgWrapper/index.js
  src/components/index.js
  src/icons/index.js
  src/icons/utils/index.js
  src/icons/utils/toIconComponent.jsx
  src/index.js
Labels: minor

#105 MOON-88: Fix flex layout
  src/globals/_layout.scss
Labels: bug

#106 QA-12658: Remove height:100% to the vertical separator
  .stylelintrc.json
  src/components/Separator/Separator.scss
  src/components/Separator/Separator.stories.jsx
  src/layouts/app/LayoutApp.stories.jsx
  src/layouts/module/LayoutModule.stories.jsx
  src/utils/_helpers.scss
Labels: bug

#109 MOON-93: Update icons
  src/tokens/icons/asset/AddCircle.svg
  src/tokens/icons/asset/PanelFixed.svg
  src/tokens/icons/asset/PanelOverlay.svg
  src/tokens/icons/asset/Paste.svg
  src/tokens/icons/asset/index.js
Labels: patch

#108 MOON-49: Add Breadcrumb component
  src/__storybook__/storybook.scss
  src/components/Breadcrumb/Breadcrumb.jsx
  src/components/Breadcrumb/Breadcrumb.md
  src/components/Breadcrumb/Breadcrumb.scss
  src/components/Breadcrumb/Breadcrumb.spec.js
  src/components/Breadcrumb/Breadcrumb.stories.jsx
  src/components/Breadcrumb/BreadcrumbItem/BreadcrumbItem.jsx
  src/components/Breadcrumb/BreadcrumbItem/BreadcrumbItem.scss
  src/components/Breadcrumb/BreadcrumbItem/BreadcrumbItem.spec.js
  src/components/Breadcrumb/BreadcrumbItem/index.js
  src/components/Breadcrumb/index.js
  src/components/Button/Button.jsx
  src/components/index.js
Labels: minor

#113 MOON-71: Fixed resizable secondary nav : force flexBasis to 0
  package.json
  src/components/SecondaryNav/SecondaryNav.jsx
  yarn.lock
Labels: bug

#110 MOON-89: Fix error 404 with an image from PrimaryNav in a story
  src/components/PrimaryNav/PrimaryNav.stories.jsx
Labels: bug

#111 MOON-95: Add component props to LayoutModule
  src/layouts/module/LayoutModule.jsx
  src/layouts/module/LayoutModule.spec.jsx
Labels: enhancement

#115 MOON-96: Fix displaying one button inside a ButtonGroup
  src/components/ButtonGroup/ButtonGroup.scss
  src/components/ButtonGroup/ButtonGroup.stories.jsx
Labels: bug

#116 BACKLOG-12710 add property invisible to the Separator so that we can hide it it is the first-child, last-child or only-child
  src/components/Separator/Separator.jsx
  src/components/Separator/Separator.scss
  src/components/Separator/Separator.spec.js
  src/components/Separator/Separator.stories.jsx
Labels: minor

#117 BACKLOG-12710 add fourth option to hide the separator if it's the first OR last child
  src/components/Separator/Separator.jsx
  src/components/Separator/Separator.scss
  src/components/Separator/Separator.spec.js
Labels: patch

#121 BACKLOG-12798 pass icon props to the icon so if we are using some mandatory attribute like src, the icon will be displayed correctly
  src/components/ListItem/ListItem.jsx
Labels: patch

#122 MOON-103: Fix error on Layout/Demo story
  src/data/treeDataNested.js
Labels: bug

#126 MOON-105: Unify button height for the small variant
  src/components/Button/Button.scss
Labels: bug

#125 MOON-104: Fix menu overflow with Safari
  src/components/Menu/Menu.scss
Labels: bug

#129 MOON-106: Design improvements
  src/components/Accordion/AccordionItem/AccordionItem.scss
  src/components/ListItem/ListItem.stories.jsx
  src/components/Menu/MenuItem.scss
  src/components/TabItem/variants/_ghost.scss
  src/components/Typography/Typography.scss
  src/globals/_init.scss
  src/tokens/colors/_colors.scss
  src/tokens/colors/color.stories.jsx
  src/tokens/colors/colors.stories.scss
Labels: bug

#132 MOON-113: Fix the key of Breadcrumb
  src/components/Breadcrumb/Breadcrumb.jsx
Labels: bug

#133 MOON-112: Design improvements
  src/components/Accordion/AccordionItem/AccordionItem.scss
  src/components/Button/variants/_default.scss
  src/components/Button/variants/_ghost.scss
  src/components/PrimaryNav/PrimaryNav.jsx
  src/components/PrimaryNav/PrimaryNav.scss
  src/components/PrimaryNav/PrimaryNav.stories.jsx
  src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.scss
  src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.stories.jsx
  src/components/TabItem/variants/_ghost.scss
Labels: bug

#131 MOON-111: Remove focus after clicking on a button
  src/components/Button/Button.jsx
Labels: bug
