Repository Jahia/moonstone, pull requests merged in 2021-01, with the labels that each got.

#219 MOON-233: Fix for component description not appearing in Docs tab
  .storybook/preview.js
  package.json
  src/components/Menu/Menu.stories.jsx
  yarn.lock
Labels: documentation

#221 TECH-338: Convert Chip component to typescript
  src/components/Chip/Chip.jsx
  src/components/Chip/Chip.stories.jsx
  src/components/Chip/Chip.tsx
  src/components/Chip/Chip.types.ts
Labels: internal

#222 TECH-337: Convert ButtonGroup component to typescript
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/ButtonGroup/ButtonGroup.types.ts
Labels: internal

#218 MOON-220: Avoid to render something when the component is empty
  src/components/Accordion/Accordion.jsx
  src/components/Accordion/Accordion.spec.js
  src/components/Badge/Badge.spec.js
  src/components/Badge/Badge.tsx
  src/components/Breadcrumb/Breadcrumb.jsx
  src/components/Breadcrumb/Breadcrumb.spec.js
  src/components/ButtonGroup/ButtonGroup.spec.js
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/Menu/Menu.spec.js
  src/components/Menu/Menu.tsx
  src/components/Tab/Tab.jsx
  src/components/Tab/Tab.spec.js
  src/components/TreeView/TreeView.jsx
  src/components/TreeView/TreeView.spec.js
  src/components/Typography/Typography.spec.js
  src/components/Typography/Typography.tsx
Labels: minor

#223 TECH-334: Convert Breadcrumb & BreadcrumbItem to Typescript
  src/components/Breadcrumb/Breadcrumb.jsx
  src/components/Breadcrumb/Breadcrumb.tsx
  src/components/Breadcrumb/Breadcrumb.types.ts
  src/components/Breadcrumb/BreadcrumbItem/BreadcrumbItem.jsx
  src/components/Breadcrumb/BreadcrumbItem/BreadcrumbItem.tsx
  src/components/Breadcrumb/BreadcrumbItem/BreadcrumbItem.types.ts
Labels: internal
