Repository Jahia/moonstone, pull requests merged in 2021-02, with the labels that each got.

#224 TECH-345: Migrate Tab & TabItem to Typescript
  src/components/Tab/Tab.stories.jsx
  src/components/Tab/Tab.tsx
  src/components/Tab/Tab.types.ts
  src/components/Tab/TabItem/TabItem.md
  src/components/Tab/TabItem/TabItem.scss
  src/components/Tab/TabItem/TabItem.spec.js
  src/components/Tab/TabItem/TabItem.stories.jsx
  src/components/Tab/TabItem/TabItem.tsx
  src/components/Tab/TabItem/TabItem.types.ts
  src/components/Tab/TabItem/index.ts
  src/components/Tab/TabItem/variants/_ghost.scss
  src/components/TabItem/TabItem.jsx
  src/components/index.ts
Labels: internal

#225 TECH-347: Migrate LayoutApp & LayoutModule to Typescript
  src/layouts/app/LayoutApp.tsx
  src/layouts/app/LayoutApp.types.ts
  src/layouts/module/LayoutModule.jsx
  src/layouts/module/LayoutModule.tsx
  src/layouts/module/LayoutModule.types.ts
Labels: internal

#228 MOON-266: Remove the diamond variant for the Badge component
  src/components/Badge/Badge.scss
  src/components/Badge/Badge.spec.js
  src/components/Badge/Badge.stories.jsx
  src/components/Badge/Badge.tsx
  src/components/Badge/Badge.types.ts
Labels: minor

#226 TECH-342: Migrate ResizableBox to Typescript
  .eslintignore
  src/components/ResizableBox/ResizableBox.jsx
  src/components/ResizableBox/ResizableBox.spec.js
  src/components/ResizableBox/ResizableBox.tsx
  src/components/ResizableBox/ResizableBox.types.ts
Labels: minor

#227 MOON-264: Create the Loader components
  .storybook/main.js
  package.json
  src/components/Loader/Loader.scss
  src/components/Loader/Loader.spec.js
  src/components/Loader/Loader.stories.tsx
  src/components/Loader/Loader.tsx
  src/components/Loader/Loader.types.ts
  src/components/Loader/index.ts
  src/components/index.ts
  yarn.lock
Labels: minor

#229 MOON-268: Add a loading state to LayoutModule
  src/components/Loader/Loader.tsx
  src/layouts/module/LayoutModule.spec.jsx
  src/layouts/module/LayoutModule.stories.jsx
  src/layouts/module/LayoutModule.tsx
  src/layouts/module/LayoutModule.types.ts
Labels: minor

#230 MOON-270: Rename classnames to clsx
  src/components/Accordion/AccordionItem/AccordionItem.jsx
  src/components/Accordion/ControlledAccordion.jsx
  src/components/Badge/Badge.stories.jsx
  src/components/Badge/Badge.tsx
  src/components/Breadcrumb/Breadcrumb.stories.jsx
  src/components/Breadcrumb/Breadcrumb.tsx
  src/components/Breadcrumb/BreadcrumbItem/BreadcrumbItem.tsx
  src/components/Button/Button.stories.jsx
  src/components/Button/Button.tsx
  src/components/ButtonGroup/ButtonGroup.stories.jsx
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/Chip/Chip.stories.jsx
  src/components/Chip/Chip.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/GlobalStyle/GlobalStyle.stories.jsx
  src/components/Input/Input.stories.jsx
  src/components/Input/Input.tsx
  src/components/ListItem/ListItem.tsx
  src/components/Menu/Menu.tsx
  src/components/Menu/MenuItem.tsx
  src/components/PrimaryNav/PrimaryNav.jsx
  src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.jsx
  src/components/PrimaryNav/PrimaryNavItemsGroup/PrimaryNavItemsGroup.jsx
  src/components/ResizableBox/ResizableBox.tsx
  src/components/SecondaryNav/SecondaryNav.jsx
  src/components/SecondaryNav/SecondaryNavHeader/SecondaryNavHeader.jsx
  src/components/Separator/Separator.stories.jsx
  src/components/Separator/Separator.tsx
  src/components/Tab/Tab.stories.jsx
  src/components/Tab/Tab.tsx
  src/components/Tab/TabItem/TabItem.stories.jsx
  src/components/Tab/TabItem/TabItem.tsx
  src/components/TreeView/ControlledTreeView.jsx
  src/components/Typography/Typography.stories.jsx
  src/components/Typography/Typography.tsx
  src/icons/Icons.stories.jsx
  src/layouts/app/LayoutApp.tsx
  src/layouts/module/LayoutModule.tsx
  src/tokens/colors/color.stories.jsx
  src/tokens/spacings/spacing.stories.jsx
Labels: internal

#231 MOON-271: Add a loading state to LayoutApp
  src/layouts/app/LayoutApp.spec.jsx
  src/layouts/app/LayoutApp.stories.jsx
  src/layouts/app/LayoutApp.tsx
  src/layouts/app/LayoutApp.types.ts
Labels: minor

#232 MOON-272: Fix Dropdown Arrow Alignment
  src/components/Dropdown/Dropdown.stories.jsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/Dropdown.types.ts
  src/components/ListItem/ListItem.tsx
Labels: bug
