Repository Jahia/moonstone, pull requests merged in 2021-12, with the labels that each got.

#278 MOON-321: Add Controlled/Uncontrolled Input
  src/components/Input/ControlledInput.tsx
  src/components/Input/Input.spec.js
  src/components/Input/Input.stories.jsx
  src/components/Input/Input.tsx
  src/components/Input/Input.types.ts
  src/components/Input/UncontrolledInput.tsx
  src/components/Menu/Menu.spec.js
Labels: patch

#280 MOON-293: Refactored checkbox component
  package.json
  src/components/Checkbox/Checkbox.scss
  src/components/Checkbox/Checkbox.spec.js
  src/components/Checkbox/Checkbox.stories.tsx
  src/components/Checkbox/Checkbox.tsx
  src/components/Checkbox/Checkbox.types.ts
  src/components/Checkbox/ControlledCheckbox.tsx
  src/components/Checkbox/ControlledCheckbox.types.ts
  src/components/Checkbox/UncontrolledCheckbox.tsx
  src/components/Checkbox/UncontrolledCheckbox.types.ts
  src/components/Table/Table.stories.jsx
  yarn.lock
Labels: major

#283 MOON-323: Fix disabled and read-only checkbox state
  src/components/Checkbox/Checkbox.spec.js
  src/components/Checkbox/ControlledCheckbox.tsx
Labels: bug

#263 MOON-305: POC for treeview in dropdown
  src/components/Dropdown/Dropdown.scss
  src/components/Dropdown/Dropdown.stories.jsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/Dropdown.types.ts
  src/components/Dropdown/DropdownMenu.tsx
  src/components/Dropdown/DropdownMenu.types.tsx
  src/components/Dropdown/TreeViewMenu.tsx
  src/components/Dropdown/TreeViewMenu.types.ts
  src/components/Menu/Menu.types.ts
  src/components/TreeView/ControlledTreeView.tsx
  src/components/TreeView/TreeView.md
  src/components/TreeView/TreeView.scss
  src/components/TreeView/TreeView.types.ts
  src/data/treeData.js
Labels: minor
