Repository Jahia/moonstone, pull requests merged in 2021-03, with the labels that each got.

#233 MOON-273: Fix LayoutModule role-busy error
  src/layouts/module/LayoutModule.tsx
Labels: bug

#234 TECH-339: Migrate GlobalStyle, ImgWrapper, and SvgWrapper components to Typescript
  src/components/GlobalStyle/GlobalStyle.d.ts
  src/components/GlobalStyle/GlobalStyle.tsx
  src/components/ImgWrapper/ImgWrapper.d.ts
  src/components/ImgWrapper/ImgWrapper.jsx
  src/components/ImgWrapper/ImgWrapper.stories.jsx
  src/components/ImgWrapper/ImgWrapper.tsx
  src/components/ImgWrapper/ImgWrapper.types.ts
  src/components/SvgWrapper/SvgWrapper.jsx
  src/components/SvgWrapper/SvgWrapper.stories.jsx
  src/components/SvgWrapper/SvgWrapper.tsx
  src/components/SvgWrapper/SvgWrapper.types.ts
Labels: internal

#235 TECH-343: Migrate SecondaryNav and SecondaryNavHeader to Typescript
  src/components/SecondaryNav/SecondaryNav.tsx
  src/components/SecondaryNav/SecondaryNav.types.ts
  src/components/SecondaryNav/SecondaryNavHeader/SecondaryNavHeader.d.ts
  src/components/SecondaryNav/SecondaryNavHeader/SecondaryNavHeader.tsx
  src/components/SecondaryNav/SecondaryNavHeader/SecondaryNavHeader.types.ts
Labels: internal

#236 TECH-341: Migrate PrimaryNav, PrimaryNavItem, and PrimaryNavItemsGroup to Typescript
  src/components/PrimaryNav/PrimaryNav.context.d.ts
  src/components/PrimaryNav/PrimaryNav.context.js
  src/components/PrimaryNav/PrimaryNav.context.ts
  src/components/PrimaryNav/PrimaryNav.d.ts
  src/components/PrimaryNav/PrimaryNav.tsx
  src/components/PrimaryNav/PrimaryNav.types.ts
  src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.jsx
  src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.tsx
  src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.types.ts
  src/components/PrimaryNav/PrimaryNavItemsGroup/PrimaryNavItemsGroup.tsx
  src/components/PrimaryNav/PrimaryNavItemsGroup/PrimaryNavItemsGroup.types.ts
Labels: internal

#237 TECH-346: Migrate TreeView and related components to Typescript
  src/components/TreeView/ControlledTreeView.tsx
  src/components/TreeView/ControlledTreeView.types.ts
  src/components/TreeView/TreeView.jsx
  src/components/TreeView/TreeView.tsx
  src/components/TreeView/TreeView.types.ts
  src/components/TreeView/UncontrolledTreeView.jsx
  src/components/TreeView/UncontrolledTreeView.tsx
  src/components/TreeView/UncontrolledTreeView.types.ts
Labels: internal

#238 TECH-333 : move Accordion components to typeScript
  src/components/Accordion/Accordion.context.d.ts
  src/components/Accordion/Accordion.context.js
  src/components/Accordion/Accordion.context.ts
  src/components/Accordion/Accordion.jsx
  src/components/Accordion/Accordion.stories.jsx
  src/components/Accordion/Accordion.tsx
  src/components/Accordion/Accordion.types.ts
  src/components/Accordion/AccordionItem/AccordionItem.d.ts
  src/components/Accordion/AccordionItem/AccordionItem.tsx
  src/components/Accordion/AccordionItem/AccordionItem.types.ts
  src/components/Accordion/ControlledAccordion.jsx
  src/components/Accordion/ControlledAccordion.tsx
  src/components/Accordion/ControlledAccordion.types.ts
  src/components/Accordion/UncontrolledAccordion.jsx
  src/components/Accordion/UncontrolledAccordion.tsx
  src/components/Accordion/UncontrolledAccordion.types.ts
Labels: internal

#239 TECH-349: Typescript format cleanup
  package.json
  src/components/Breadcrumb/Breadcrumb.tsx
  src/components/Breadcrumb/BreadcrumbItem/BreadcrumbItem.tsx
  src/components/Button/Button.tsx
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/Chip/Chip.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/Dropdown.types.ts
  src/components/Input/Input.stories.jsx
  src/components/Input/Input.tsx
  src/components/Input/Input.types.ts
  src/components/ListItem/ListItem.tsx
  src/components/ListItem/ListItem.types.ts
  src/components/Loader/Loader.tsx
  src/components/Menu/Menu.tsx
  src/components/Menu/Menu.types.ts
  src/components/Menu/MenuItem.tsx
  src/components/Menu/MenuItem.types.ts
  src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.types.ts
  src/components/ResizableBox/ResizableBox.types.ts
  src/components/Separator/Separator.stories.jsx
  src/components/Separator/Separator.tsx
  src/components/Separator/Separator.types.ts
  src/components/SvgWrapper/SvgWrapper.types.ts
  src/components/Tab/Tab.tsx
  src/components/Tab/TabItem/TabItem.tsx
  src/components/TreeView/ControlledTreeView.types.ts
  src/components/Typography/Typography.spec.js
  src/components/Typography/Typography.stories.jsx
  src/components/Typography/Typography.tsx
  src/components/Typography/Typography.types.ts
  src/hooks/useEnterExitCallbacks.tsx
  yarn.lock
Labels: internal

#240 MOON-256: Create the Header component
  .storybook/main.js
  src/components/Header/Header.scss
  src/components/Header/Header.spec.js
  src/components/Header/Header.stories.jsx
  src/components/Header/Header.tsx
  src/components/Header/Header.types.ts
  src/components/Header/index.ts
  src/components/Loader/Loader.stories.tsx
  src/components/index.ts
Labels: minor
