Repository Jahia/moonstone, pull requests merged in 2022-12, with the labels that each got.

#336 MOON-360: Add icon FileBroken
  src/icons/assets/FileBroken.svg
  src/icons/components/FileBroken.tsx
  src/icons/components/index.tsx
Labels: patch

#338 Fixed observer registration
  src/components/Collapsible/ControlledCollapsible.tsx
Labels: bug

#340 Set fetch depth to 0 (all history)
  .github/workflows/on-merge.yml
Labels: internal

#344 BACKLOG-20485: reorganized and fixed dnd
  src/components/ListItem/ListItem.types.ts
  src/components/ListSelector/ListSelector.tsx
  src/components/ListSelector/ValueList/ValueList.scss
  src/components/ListSelector/ValueList/ValueList.tsx
  src/components/ListSelector/ValueList/ValueList.types.ts
Labels: bug

#345 MOON-362: Add story for Dropdown with description
  src/components/Dropdown/Dropdown.stories.jsx
  src/components/ListItem/ListItem.stories.tsx
  src/components/Menu/Menu.stories.tsx
Labels: bug
