Repository Jahia/moonstone, pull requests merged in 2022-07, with the labels that each got.

#301 MOON-341: Manage isReversed to SecondaryNav
  src/components/Accordion/AccordionItem/AccordionItem.scss
  src/components/SecondaryNav/SecondaryNav.scss
  src/components/SecondaryNav/SecondaryNav.tsx
  src/components/SecondaryNav/SecondaryNav.types.ts
  src/layouts/Layouts.stories.jsx
  src/layouts/content/LayoutContent.scss
  src/layouts/content/LayoutContent.tsx
Labels: patch

#298 TECH-568 migrate moonstone to github action
  .circleci/config.yml
  .github/workflows/on-code-change.yml
  .github/workflows/on-merge.yml
Labels: internal

#302 MOON-340: Remove husky
  .husky/pre-commit
  .husky/pre-push
  package.json
  yarn.lock
Labels: internal

#305 TECH-568: Fix release workflow
  .autorc
  .github/workflows/on-merge.yml
  package.json
Labels: bug, internal

#306 MOON-342: Update auto dependency
  package.json
  yarn.lock
Labels: patch, dependencies
