Repository Jahia/moonstone, pull requests merged in 2024-11, with the labels that each got.

#451 MOON-451: Add component ButtonToggle
  src/components/ButtonToggle/ButtonToggle.md
  src/components/ButtonToggle/ButtonToggle.scss
  src/components/ButtonToggle/ButtonToggle.spec.js
  src/components/ButtonToggle/ButtonToggle.stories.tsx
  src/components/ButtonToggle/ButtonToggle.tsx
  src/components/ButtonToggle/ButtonToggle.types.ts
  src/components/ButtonToggle/ControlledButtonToggle.tsx
  src/components/ButtonToggle/UncontrolledButtonToggle.tsx
  src/components/ButtonToggle/index.ts
  src/components/index.ts
Labels: minor

#449 MOON-455: Remove react-docgen-typescript-loader
  package.json
  yarn.lock
Labels: dependencies

#453 MOON-449: Upgrade to yarn 4
  .github/workflows/deploy-storybook.yml
  .github/workflows/on-code-change.yml
  .github/workflows/on-merge.yml
  .gitignore
  .storybook/main.js
  .yarn/releases/yarn-4.5.1.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: internal

#457 MOON-460: Add readonly state to TreeView item
  .eslintrc
  package.json
  src/components/Checkbox/Checkbox.stories.tsx
  src/components/CheckboxGroup/CheckboxItem/CheckboxItem.stories.tsx
  src/components/Collapsible/Collapsible.stories.tsx
  src/components/Dropdown/Dropdown.stories.jsx
  src/components/Input/Input.stories.tsx
  src/components/Input/SearchContextInput/SearchContextInput.stories.tsx
  src/components/ListSelector/ListSelector.stories.tsx
  src/components/RadioGroup/RadioGroup.stories.tsx
  src/components/Switch/Switch.stories.tsx
  src/components/Tab/Tab.stories.tsx
  src/components/Table/Table.stories.jsx
  src/components/TreeView/ControlledTreeView.tsx
  src/components/TreeView/TreeView.scss
  src/components/TreeView/TreeView.spec.tsx
  src/components/TreeView/TreeView.stories.jsx
  src/components/TreeView/TreeView.stories.scss
  src/components/TreeView/TreeView.types.ts
  src/data/treeData.js
  yarn.lock
Labels: patch

#459 MOON-458: Add new colors & variants to Chip component
  src/components/Chip/Chip.scss
  src/components/Chip/Chip.stories.tsx
  src/components/Chip/Chip.tsx
  src/components/Chip/Chip.types.ts
Labels: patch
