Repository Jahia/moonstone, pull requests merged in 2025-05, with the labels that each got.

#1031 chore: sync files with `Jahia/.github` [skip ci]
  .github/ISSUE_TEMPLATE/release.md
Labels: chore

#1036 build: Create hybrid package, provide esm, cjs artifacts
  package.json
  vite.config.mjs
Labels: minor

#1038 fix: cardSelector disabled style
  src/components/CardSelector/CardSelector.scss
  src/components/CardSelector/CardSelector.tsx
Labels: patch

#1041 fix: use the same height for CardSelector and EmptyCardSelector
  src/components/CardSelector/CardSelector.scss
  src/components/CardSelector/EmptyCardSelector/EmptyCardSelector.scss
Labels: patch

#1042 fix: storybook config
  .storybook/main.ts
Labels: internal

#1046 fix: aria-label on button that toggle the PrimaryNav
  src/components/PrimaryNav/PrimaryNav.spec.tsx
  src/components/PrimaryNav/PrimaryNav.tsx
Labels: patch, a11y

#1049 fix: Prevent focus style after clicking or selecting an item
  src/components/Accordion/AccordionItem/AccordionItem.scss
  src/components/ButtonToggle/ButtonToggle.scss
  src/components/CardSelector/EmptyCardSelector/EmptyCardSelector.scss
  src/components/Input/BaseInput/BaseInput.scss
  src/components/Menu/MenuItem.scss
  src/components/RadioGroup/RadioItem/RadioItem.scss
  src/components/Textarea/Textarea.scss
Labels: patch

#1048 fix: prevent selection on TreeView item when clicking on the chevron
  src/components/TreeView/ControlledTreeView.tsx
  src/components/TreeView/TreeView.spec.tsx
  src/hooks/useToggleNode.spec.tsx
  src/hooks/useToggleNode.tsx
Labels: patch

#1051 feat: allow icon component as thumbnail
  src/components/CardSelector/CardSelector.spec.tsx
  src/components/CardSelector/CardSelector.stories.tsx
  src/components/CardSelector/CardSelector.tsx
  src/components/CardSelector/CardSelector.types.ts
Labels: minor

#1052 chore: sync files with `Jahia/.github` [skip ci]
  .github/ISSUE_TEMPLATE/story.md
Labels: chore
