Repository Jahia/moonstone, pull requests merged in 2025-10, with the labels that each got.

#1146 chore: migration PrimaryNavItemsGroup in typescript
  src/components/PrimaryNav/PrimaryNavItemsGroup/PrimaryNavItemsGroup.stories.jsx
  src/components/PrimaryNav/PrimaryNavItemsGroup/PrimaryNavItemsGroup.stories.tsx
Labels: internal

#1148 chore: Migration treeview story file in typescript
  src/components/TreeView/TreeView.stories.tsx
Labels: internal

#1141 feat: Add group titles to Dropdown search results
  src/components/Dropdown/Dropdown.spec.tsx
  src/components/Menu/Menu.spec.tsx
  src/components/Menu/Menu.tsx
Labels: patch

#1100 feat: add new component Modal
  src/components/Modal/Modal.md
  src/components/Modal/Modal.scss
  src/components/Modal/Modal.spec.tsx
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/Modal.types.ts
  src/components/Modal/ModalBody/ModalBody.scss
  src/components/Modal/ModalBody/ModalBody.spec.tsx
  src/components/Modal/ModalBody/ModalBody.tsx
  src/components/Modal/ModalBody/ModalBody.types.ts
  src/components/Modal/ModalFooter/ModalFooter.scss
  src/components/Modal/ModalFooter/ModalFooter.spec.tsx
  src/components/Modal/ModalFooter/ModalFooter.tsx
  src/components/Modal/ModalFooter/ModalFooter.types.ts
  src/components/Modal/ModalHeader/ModalHeader.scss
  src/components/Modal/ModalHeader/ModalHeader.spec.tsx
  src/components/Modal/ModalHeader/ModalHeader.tsx
  src/components/Modal/ModalHeader/ModalHeader.types.ts
  src/components/Modal/index.ts
  src/components/index.ts
Labels: minor
