Repository Jahia/moonstone, pull requests merged in 2025-03, with the labels that each got.

#972 chore: sync files with `Jahia/.github` [skip ci]
  .github/ISSUE_TEMPLATE/release.md
  .github/release.yml
Labels: chore

#973 chore: unify ghost variant styling
  src/components/Breadcrumb/BreadcrumbItem/BreadcrumbItem.spec.js
  src/components/Button/Button.scss
  src/components/Button/Button.spec.js
  src/components/Button/Button.tsx
  src/components/Button/variants/_default.scss
  src/components/Button/variants/_ghost.scss
  src/components/Button/variants/_outlined.scss
  src/components/ButtonGroup/ButtonGroup.spec.js
  src/components/ButtonToggle/ButtonToggle.scss
  src/components/ButtonToggle/ButtonToggle.spec.js
  src/components/ButtonToggle/ControlledButtonToggle.tsx
  src/components/Dropdown/Dropdown.scss
  src/components/Tab/Tab.stories.tsx
  src/components/Tab/TabItem/TabItem.scss
  src/components/Tab/TabItem/TabItem.spec.js
  src/components/Tab/TabItem/TabItem.tsx
  src/components/Tab/TabItem/TabItem.types.ts
  src/components/Tab/TabItem/variants/_ghost.scss
  src/globals.scss
  src/globals/_variants.scss
Labels: patch

#974 chore: unify disabled & read-only styling
  src/components/Dropdown/Dropdown.scss
  src/components/Dropdown/Dropdown.tsx
  src/components/Input/BaseInput/BaseInput.scss
  src/components/Menu/MenuItem.scss
  src/components/Textarea/ControlledTextarea.tsx
  src/components/Textarea/Textarea.scss
  src/utils/_mixins.scss
Labels: patch

#980 chore: sync files with `Jahia/.github` [skip ci]
  .github/ISSUE_TEMPLATE/release.md
Labels: chore

#979 feat(component): add Tooltip with new dependency react floating UI
  package.json
  src/components/Tooltip/Tooltip.scss
  src/components/Tooltip/Tooltip.spec.js
  src/components/Tooltip/Tooltip.stories.tsx
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/Tooltip.types.tsx
  src/components/Tooltip/index.ts
  src/components/index.ts
  yarn.lock
Labels: minor

#983 feat: improve the loading of tree items
  src/components/TreeView/ControlledTreeView.tsx
  src/components/TreeView/TreeView.spec.tsx
  src/components/TreeView/TreeView.stories.jsx
Labels: patch

#986 feat: new icon named VisibilityCondition
  src/icons/assets/VisibilityCondition.svg
  src/icons/components/VisibilityCondition.tsx
  src/icons/components/index.ts
Labels: patch

#987 fix: keep hover style when I right-click on a row
  src/components/Button/Button.tsx
  src/components/Table/TableRow/TableRow.scss
  src/components/Table/TableRow/TableRow.tsx
Labels: patch

#991 fix: color issues with last moonstone release
  src/components/Button/variants/_default.scss
  src/components/ButtonGroup/ButtonGroup.scss
  src/components/ButtonGroup/ButtonGroup.spec.js
  src/components/ButtonGroup/ButtonGroup.stories.tsx
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/Dropdown/Dropdown.scss
  src/globals/_variants.scss
Labels: patch

#996 feat: new icons ChevronFirstList and ChevronLastList
  src/icons/assets/ChevronFirstList.svg
  src/icons/assets/ChevronLastList.svg
  src/icons/components/ChevronFirstList.tsx
  src/icons/components/ChevronLastList.tsx
  src/icons/components/index.ts
Labels: patch, icon

#995 feat: new icons AdvancedEdit, Rename, EditImage
  src/icons/assets/AdvancedEdit.svg
  src/icons/assets/EditImage.svg
  src/icons/assets/Rename.svg
  src/icons/components/AdvancedEdit.tsx
  src/icons/components/EditImage.tsx
  src/icons/components/Rename.tsx
  src/icons/components/index.ts
Labels: patch, icon
