Repository Jahia/moonstone, pull requests merged in 2025-04, with the labels that each got.

#1002 feat: Improve cardSelector
  src/components/CardSelector/CardSelector.scss
  src/components/CardSelector/CardSelector.spec.js
  src/components/CardSelector/CardSelector.tsx
  src/components/CardSelector/CardSelector.types.ts
  src/components/CardSelector/EmptyCardSelector/EmptyCardSelector.scss
  src/components/Fieldset/Fieldset.stories.tsx
Labels: patch

#1007 build: produce sbom
  package.json
  vite.config.mjs
  yarn.lock
Labels: patch

#1015 chore: sync files with `Jahia/.github` [skip ci]
  .github/ISSUE_TEMPLATE/release.md
  .github/ISSUE_TEMPLATE/story.md
  .github/ISSUE_TEMPLATE/tech-day.md
Labels: chore

#1018 chore: sync files with `Jahia/.github` [skip ci]
  .github/ISSUE_TEMPLATE/tech-day.md
Labels: chore

#1019 chore: sync files with `Jahia/.github` [skip ci]
  .github/ISSUE_TEMPLATE/release.md
Labels: chore

#1025 fix: outlined dropdown background on hover
  src/components/Dropdown/Dropdown.scss
Labels: patch

#1029 chore: Migrate Header stories to Typescript
  src/components/Header/Header.stories.tsx
Labels: skip-release, internal
