Repository Jahia/moonstone, pull requests merged in 2025-01, with the labels that each got.

#470 MOON-472: Add border radius variables for selectors
  src/components/Badge/Badge.scss
  src/components/Button/Button.scss
  src/components/ButtonGroup/ButtonGroup.scss
  src/components/CardSelector/CardSelector.scss
  src/components/CardSelector/EmptyCardSelector/EmptyCardSelector.scss
  src/components/Checkbox/Checkbox.scss
  src/components/Dropdown/Dropdown.scss
  src/components/Input/BaseInput/BaseInput.scss
  src/components/ListSelector/ValueList/ValueList.scss
  src/components/Menu/Menu.scss
  src/components/Paper/Paper.scss
  src/components/Pill/Pill.scss
  src/components/PrimaryNav/PrimaryNavItem/PrimaryNavItem.scss
  src/components/Tab/TabItem/TabItem.scss
  src/components/Tag/Tag.scss
  src/tokens/borders/_borders.scss
Labels: patch

#473 chore: sync files with `Jahia/.github` [skip ci]
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/epic.md
  .github/ISSUE_TEMPLATE/other.md
  .github/ISSUE_TEMPLATE/release.md
  .github/ISSUE_TEMPLATE/spike.md
  .github/ISSUE_TEMPLATE/story.md
  .github/ISSUE_TEMPLATE/support.yml
  .github/ISSUE_TEMPLATE/tech-day.md
  .github/release.yml
  .github/workflows/delivery-issue-chores.yml
Labels: chore

#475 chore: sync files with `Jahia/.github` [skip ci]
  .github/workflows/delivery-issue-chores.yml
Labels: chore

#472 MOON-471: Create Textarea component
  src/components/Textarea/ControlledTextarea.tsx
  src/components/Textarea/Textarea.md
  src/components/Textarea/Textarea.scss
  src/components/Textarea/Textarea.spec.js
  src/components/Textarea/Textarea.stories.tsx
  src/components/Textarea/Textarea.tsx
  src/components/Textarea/Textarea.types.ts
  src/components/Textarea/UncontrolledTextarea.tsx
  src/components/Textarea/index.ts
  src/components/index.ts
  src/icons/assets/Paragraph.svg
  src/icons/components/Paragraph.tsx
  src/icons/components/index.ts
Labels: minor

#477 MOON-476: Unify the styling of selectors
  src/components/CardSelector/CardSelector.scss
  src/components/CardSelector/EmptyCardSelector/EmptyCardSelector.scss
  src/components/Dropdown/Dropdown.scss
  src/components/Field/Field.stories.tsx
  src/components/Header/Header.scss
  src/components/Input/BaseInput/BaseInput.scss
  src/components/ListSelector/ValueList/ValueList.scss
  src/components/Textarea/Textarea.scss
  src/globals.scss
  src/globals/_variables.scss
  src/tokens/borders/_borders.scss
Labels: patch

#479 chore: sync files with `Jahia/.github` [skip ci]
  .github/ISSUE_TEMPLATE/release.md
Labels: chore

#480 MOON-478: Fix issue with long text in Header and Breadcrumb
  src/components/Breadcrumb/Breadcrumb.scss
  src/components/Breadcrumb/Breadcrumb.tsx
  src/components/Breadcrumb/BreadcrumbItem/BreadcrumbItem.scss
  src/components/Breadcrumb/BreadcrumbItem/BreadcrumbItem.stories.tsx
  src/components/Header/Header.scss
Labels: patch

#481 chore: sync files with `Jahia/.github` [skip ci]
  .github/ISSUE_TEMPLATE/release.md
Labels: chore

#483 MOON-480: Fix issue with Dropdown width
  src/components/Field/FieldSelector/FieldSelector.scss
Labels: patch

#482 MOON-479: Fix border styling
  src/components/Dropdown/Dropdown.scss
  src/components/Input/BaseInput/BaseInput.scss
  src/components/Textarea/Textarea.scss
  src/globals/_variables.scss
Labels: patch

#478 MOON-475: Add components Fieldset & DynamicFieldset
  src/components/Fieldset/DynamicFieldset/ControlledDynamicFieldset.tsx
  src/components/Fieldset/DynamicFieldset/DynamicFieldset.md
  src/components/Fieldset/DynamicFieldset/DynamicFieldset.spec.js
  src/components/Fieldset/DynamicFieldset/DynamicFieldset.stories.tsx
  src/components/Fieldset/DynamicFieldset/DynamicFieldset.tsx
  src/components/Fieldset/DynamicFieldset/DynamicFieldset.types.ts
  src/components/Fieldset/DynamicFieldset/UncontrolledDynamicFieldset.tsx
  src/components/Fieldset/DynamicFieldset/index.ts
  src/components/Fieldset/Fieldset.md
  src/components/Fieldset/Fieldset.scss
  src/components/Fieldset/Fieldset.spec.js
  src/components/Fieldset/Fieldset.stories.tsx
  src/components/Fieldset/Fieldset.tsx
  src/components/Fieldset/Fieldset.types.ts
  src/components/Fieldset/index.ts
Labels: minor

#485 chore: sync files with `Jahia/.github` [skip ci]
  .github/ISSUE_TEMPLATE/tech-day.md
Labels: chore

#488 MOON- 474: Fix controlled component story
  src/components/Fieldset/DynamicFieldset/DynamicFieldset.stories.tsx
  src/components/Input/Input.stories.tsx
  src/components/Textarea/Textarea.stories.tsx
Labels: patch

#491 MOON-481: Fix color with the ghost Button
  src/__storybook__/storybook.scss
  src/components/Button/Button.stories.tsx
  src/components/Button/variants/_ghost.scss
Labels: patch

#493 QA-15352: Fix dnd issue for ListSelector
  src/components/ListSelector/ListSelector.tsx
  src/components/ListSelector/ValueList/ValueList.tsx
Labels: patch

#926 feat: add new icon modified
  src/icons/assets/Modified.svg
  src/icons/components/Modified.tsx
  src/icons/components/index.ts
Labels: patch
